apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test
  template:
    metadata:
      labels:
        app: go-test
    spec:
      containers:
      - image: docker.io/nginx/nginx:latest
        name: webserver-simple
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-test-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-test
